# Generated by Django 5.0.7 on 2024-07-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_questions_solved",
            name="no_of_questions",
            field=models.IntegerField(default=0),
        ),
    ]
