# Generated by Django 5.0.7 on 2024-07-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_user_questions_solved_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_questions_solved", old_name="user_id_1", new_name="solver",
        ),
    ]
