# Generated by Django 5.0.7 on 2024-07-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_user_id_1_user_questions_solved_solver"),
    ]

    operations = [
        migrations.CreateModel(
            name="question_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Easy",
                        max_length=10,
                    ),
                ),
                ("sample_input", models.TextField()),
                ("sample_output", models.TextField()),
                ("constraints", models.TextField()),
            ],
        ),
    ]
