# Generated by Django 4.2.14 on 2024-07-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_user_question_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=100)),
                ("code", models.TextField()),
                ("input_data", models.TextField(blank=True, null=True)),
                ("output_data", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
